/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'v-zyon' at '15-8-18 上午11:13' with Gradle 2.5-rc-2
 *
 * @author v-zyon, @date 15-8-18 上午11:13
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
