/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'v-zyon' at '15-8-19 下午2:01' with Gradle 2.5-rc-2
 *
 * @author v-zyon, @date 15-8-19 下午2:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
